### ISSUE TITLE
ssl-cert pkg should be installed for ssl-cert group

### ISSUE THREAD

**Issue by heww** [gimoh/ansible_docker_nginx_proxy#1]
If ssl-cert pkg not installed, roles will be failed for `ssl-cert` group not exist.

``` shell
failed: [192.168.100.102] => {"failed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/pki/svc-certs", "size": 4096, "state": "directory", "uid": 0}           
msg: chgrp failed: failed to look up group ssl-cert
```

**Comment by gimoh** [comment]
Hmm, I was just going by what ubuntu does to `/etc/ssl/private/` but I suppose it doesn't really make sense as nginx within the container runs as root anyway.  I'll change that to root.
